apiVersion: v1
kind: Service
metadata:
  name: neo4j-public
  namespace: neo4j
  labels:
    app: neo4j
    component: core
spec:
  type: NodePort
  ports:
  - port: 7687
    targetPort: 7687
    name: bolt
  - port: 7474
    targetPort: 7474
    name: browser
  selector:
    app: neo4j
    component: core

